version: '2'
services:
  dev-image:
    image: "yvo-solutions/bib-dev:latest"
    ports:
      - "2000:2000"
    privileged: true
    container_name: devenv
    volumes:
      - "../..:/home/develop/dev"
